Add `delete teamdrive` command
fionera/TeamDriveManager pull request #14
Opened 2020-10-14 18:01 UTC by CatTheHacker

2020-10-17 03:18 UTC, CatTheHacker commented
need to find out how to get only files from root of the drive and delete them so it doesn't sit for hours deleting already deleted files

2020-10-26 23:39 UTC, fionera commented on cmd/delete/teamdrive.go
> +		var query string = "parents = \"" + teamdriveId + "\""
query := fmt.Sprintf(`parents = "%s"`, teamdriveId)

2020-10-26 23:40 UTC, fionera requested changes
Only this one string concation :+1:

2020-10-26 23:44 UTC, CatTheHacker commented on cmd/delete/teamdrive.go
> +		var query string = "parents = \"" + teamdriveId + "\""
Done

2020-10-26 23:44 UTC, fionera approved these changes

2020-10-26 23:44 UTC, merged